### PR TITLE
Feature/UI improvements

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Several UI improvements
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Notes

Screenshot 2023-09-22 at 12 49 22 PM

## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by baristaGeek — CHANGES_REQUESTED** [review]
The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:

1. The font with serifs doesn't look "computational" the old font was better. 

2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line. 

3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such. 

Attaching an image just in case it's something with my local setup. 

Screen Shot 2023-09-22 at 3 44 26 PM

**Comment by EstebanDalelR** [comment]
> The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:
> 
>     1. The font with serifs doesn't look "computational" the old font was better.
> 
>     2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line.
> 
>     3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such.
> 
> 
> Attaching an image just in case it's something with my local setup.
> Screen Shot 2023-09-22 at 3 44 26 PM
 On #2, please show me? I cannot reproduce
Screenshot 2023-09-26 at 10 43 20 AM

**Comment by EstebanDalelR** [comment]
> The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:
> 
>     1. The font with serifs doesn't look "computational" the old font was better.
> 
>     2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line.
> 
>     3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such.
> 
> 
> Attaching an image just in case it's something with my local setup.
> Screen Shot 2023-09-22 at 3 44 26 PM

On 1., I used Roboto Mono. I chose a mono spaced as it is the most "computational" thing I can imagine, but I can make the background green and letters green. Maybe I can try to get the terminal settings.

**Comment by EstebanDalelR** [comment]
> The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:
> 
>     1. The font with serifs doesn't look "computational" the old font was better.
> 
>     2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line.
> 
>     3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such.
> 
> 
> Attaching an image just in case it's something with my local setup.
> Screen Shot 2023-09-22 at 3 44 26 PM

on 3. I tried a pink.

**Comment by baristaGeek** [comment]
> > The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:
> > ```
> > 1. The font with serifs doesn't look "computational" the old font was better.
> > 
> > 2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line.
> > 
> > 3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Attaching an image just in case it's something with my local setup.
> > Screen Shot 2023-09-22 at 3 44 26 PM
> 
> On 1., I used Roboto Mono. I chose a mono spaced as it is the most "computational" thing I can imagine, but I can make the background green and letters green. Maybe I can try to get the terminal settings.

I don't know if it was because of the previously used font family, but the serifs the old font had didn't make it look computational enough. This font looks good now.

**Comment by baristaGeek** [comment]
> > The huge spaces that were being programmatically generated between one piece of indexed information and the next one have been removed and that LGTM. But:
> > ```
> > 1. The font with serifs doesn't look "computational" the old font was better.
> > 
> > 2. In what we currently have on the dev branch the AI summary (has good quality on our IDE extensions) is expandible. On this branch I'm only able to see the first line.
> > 
> > 3. A minor detail (it can be done later): To improve readibility of the indexed info, the font color of the title of a piece of retrieved info should be different than the one of the body of such.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Attaching an image just in case it's something with my local setup.
> > Screen Shot 2023-09-22 at 3 44 26 PM
> > On #2, please show me? I cannot reproduce
> > Screenshot 2023-09-26 at 10 43 20 AM

I've been trying as well (after pulling the new changes) and haven't been able to as well. Let's just consider it either an edge case or fixed.

**Review by baristaGeek — APPROVED** [review]

**Pull request merged**
